#!/usr/bin/env bash

###
# Script Name:  install-containerd-helpers
#
# Description: A library that containers helpers to install containerd on different
#              distributions based on a package manager
###
set -x extglob

# Steps taken from: https://docs.docker.com/install/linux/docker-ce/centos/
function install_rpm_containerd() {
    # Install containerd dependency for non-zypper dependecies
    echo "[DEBUG] Installing engine dependencies"
    ${pkg_config_manager} \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
}

# Steps taken from: https://docs.docker.com/install/linux/docker-ce/ubuntu/
function install_debian_containerd() {
    echo "[DEBUG] Installing containerd"
    curl -fsSL https://download.docker.com/linux/${DIST_ID}/gpg | apt-key add -


    if [[ ${DIST_VERSION}  == "sid" ]]; then
        DIST_VERSION='buster'
    fi
    echo "deb [arch=${ARCH}] https://download.docker.com/linux/${DIST_ID} \
        ${DIST_VERSION} \
        stable" > /etc/apt/sources.list.d/docker.list

    apt-get update
}