#!/usr/bin/env bash

set -e

shopt -s globstar

# /backends should be volume mounted from root backends dir
# /out should also be volume mounted from static/out/
for installer in /backends/*.installer; do
	bash "${installer}" build
	DESTDIR='/out' PREFIX="/" bash "${installer}" install_backend
done
