# reusable workflow
name: .build

# TODO: hide reusable workflow from the UI. Tracked in https://github.com/community/community/discussions/12025

# Default to 'contents: read', which grants actions to read commits.
#
# If any permission is set, any permission not included in the list is
# implicitly set to "none".
#
# see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
        default: "amd64"
      target:
        required: true
        type: string
      image:
        required: true
        type: string

jobs:
  # Transform the arch into a specific worker
  # amd64 -> ubuntu-22.04
  # arm64 -> ubuntu22_arm64
  prepare:
    runs-on: ubuntu-22.04
    outputs:
      worker: ${{ steps.set.outputs.worker }}
      version: ${{ steps.set.outputs.version }}
    steps:
      -
        name: Set worker
        id: set
        run: |
          echo "version=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
          case ${{ inputs.arch }} in
              amd64|static*|cross*)
              echo "worker=ubuntu-20.04" >> $GITHUB_OUTPUT
              ;;
              arm64|armhf)
              echo "worker=ubuntu22_arm64" >> $GITHUB_OUTPUT
              ;;
              *)
              echo "::error::Unsupported arch: ${{ inputs.arch }}"
              exit 1
              ;;
          esac

  build:
    needs: prepare
    runs-on: ${{ needs.prepare.outputs.worker }}
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Build
        run: |
          export VERSION=${{ needs.prepare.outputs.version }}
          export REF=master
          
          export DOCKER_BUILDX_REF=master
          export DOCKER_BUILDX_VERSION=$VERSION
          
          export DOCKER_COMPOSE_REF=main
          export DOCKER_COMPOSE_VERSION=$VERSION
          
          if [ "${{ inputs.target }}" == static ]; then
              export DOCKER_BUILD_PKGS="${{ inputs.arch }}"
          else
              export ARCH=${{ inputs.arch }}
          fi
          
          make ${{ inputs.target }}

      -
        name: Verify
        if: ${{ inputs.image != '' }}
        run: |
          export IMAGE=${{ inputs.image }}
          export ARCH=${{ inputs.arch }}
          
          if [ "$ARCH" == "armhf" ]; then
              export VERIFY_PLATFORM="--platform linux/arm/v7"
          fi

          make verify

      -
        name: Artifact deb
        uses: actions/upload-artifact@v4
        with:
          name: nightly-${{ inputs.target }}-${{ inputs.arch }}
          path: |
            deb/debbuild/${{ inputs.target }}
            rpm/rpmbuild/${{ inputs.target }}
            static/build
          retention-days: 1
