name: nightly

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch: {}

jobs:
    build:
        runs-on: selfhosted
        strategy:
            fail-fast: false
            matrix:
                target:
                    - debian-bookworm
        steps:
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -
                name: Checkout
                uses: actions/checkout@v3

            -
                name: Build
                run: |
                    export VERSION=$(date +%Y%m%d)
                    export REF=master

                    export DOCKER_BUILDX_REF=master
                    export DOCKER_BUILDX_VERSION=$VERSION

                    export DOCKER_COMPOSE_REF=main
                    export DOCKER_COMPOSE_VERSION=$VERSION

                    make ${{ matrix.target }}

            -
                name: Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: nightly-${{ matrix.target }}
                    path: deb/debbuild/${{ matrix.target }}
                    retention-days: 3
