name: nightly

on:
    workflow_dispatch:
    pull_request:

jobs:
    packages:
        strategy:
            fail-fast: false
            matrix:
                arch:
                    - amd64
                    - arm64
                dist:
                    #- {target: "debian-bullseye", image: "debian:bullseye"}
                    - {target: "debian-bookworm", image: "debian:bookworm"}
                    #- {target: "ubuntu-focal", image: "ubuntu:focal"}
                    #- {target: "ubuntu-jammy", image: "ubuntu:jammy"}
                    #- {target: "ubuntu-noble", image: "ubuntu:noble"}

                    #- {target: "centos-9", image: "quay.io/centos/centos:stream9"}
                    #- {target: "fedora-39", image: "fedora:39"}
                    #- {target: "fedora-40", image: "fedora:40"}
                    #- {target: "rhel-8", image: "registry.access.redhat.com/ubi8/ubi"}
                    #- {target: "rhel-9", image: "registry.access.redhat.com/ubi9/ubi"}
                include:
                    - arch: static-linux
                      dist: {target: "static", image: ""}
                    - arch: cross-mac
                      dist: {target: "static", image: ""}
                    - arch: cross-win
                      dist: {target: "static", image: ""}
                    - arch: armhf
                      dist: {target: "debian-bookworm", image: "debian:bookworm"}
                    #- arch: armhf
                    #  dist: {target: "debian-bullseye", image: "debian:bullseye"}
                    #- arch: armhf
                    #  dist: {target: "ubuntu-focal", image: "ubuntu:focal"}
                    #- arch: armhf
                    #  dist: {target: "ubuntu-jammy", image: "ubuntu:jammy"}
                    #- arch: armhf
                    #  dist: {target: "ubuntu-noble", image: "ubuntu:noble"}
                # TODO
                #    - arch: armhf
                #      dist: {target: "raspbian-bullseye", image: "balenalib/rpi-raspbian:bullseye"}
                #    - arch: armhf
                #      dist: {target: "raspbian-bookworm", image: "balenalib/rpi-raspbian:bookworm"}
        uses: ./.github/workflows/.nightly.yml
        with:
            arch: ${{ matrix.arch }}
            target: ${{ matrix.dist.target }}
            image: ${{ matrix.dist.image }}

